version: "3.2"
services:

  # Services in Test Group
  # ----------------------
  # TODO: describe

  # TODO: describe
  agent-test:
    build:
      context: ./agent
    environment:
      - BENCH_OUTPUT=/var/log/bench/test/agent.bytes
    volumes:
      - './output:/var/log/bench'

  # TODO: describe
  upstream-test:
    build:
      context: ./upstream
    environment:
      - BENCH_OUTPUT=/var/log/bench/test/upstream.bytes
    volumes:
      - './output:/var/log/bench'

  # TODO: describe
  tracer-test:
    image: ubuntu:22.04
    environment:
      - BENCH_OUTPUT=/var/log/bench/test/tracer.nanoseconds
      - DD_AGENT_HOST=agent-test
      - UPSTREAM=upstream-test
    volumes:
      - './output:/var/log/bench'
      - './tracer/init:/usr/local/bin/init:ro'
      - '../../.build:/opt/build:ro'
    command: /usr/local/bin/init
    depends_on:
      - 'agent-test'
      - 'upstream-test'

  # Services in Control Group
  # -------------------------
  # TODO: describe

  # TODO: describe
  agent-control:
    build:
      context: ./agent
    environment:
      - BENCH_OUTPUT=/var/log/bench/control/agent.bytes
    volumes:
      - './output:/var/log/bench'

  # TODO: describe
  upstream-control:
    build:
      context: ./upstream
    environment:
      - BENCH_OUTPUT=/var/log/bench/control/upstream.bytes
    volumes:
      - './output:/var/log/bench'

  # TODO: describe
  tracer-control:
    image: ubuntu:22.04
    environment:
      - BENCH_OUTPUT=/var/log/bench/control/tracer.nanoseconds
      - DD_AGENT_HOST=agent-control
      - UPSTREAM=upstream-control
    volumes:
      - './output:/var/log/bench'
      - './tracer/init:/usr/local/bin/init:ro'
      - '../../.build:/opt/build:ro'
    command: /usr/local/bin/init
    depends_on:
      - 'agent-control'
      - 'upstream-control'
